In [1]:
# IMPORTS
import numpy as np
import pandas as pd

#Fin Data Sources
import yfinance as yf
import pandas_datareader as pdr

#Data viz
import plotly.graph_objs as go
import plotly.graph_objects as go
import plotly.express as px

import time
from datetime import date

# for graphs
import matplotlib.pyplot as plt

### Load Dataset

Upload the saved parquet file 9`stocks_df_combined_2025_06_16.parquet`) from Module 2:

In [6]:
df_full = pd.read_parquet("../02_Data_Wrangler/stocks_df_combined_2025_06_16.parquet.brotli")

In [7]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230295 entries, 0 to 5701
Columns: 204 entries, Open to growth_btc_usd_365d
dtypes: datetime64[ns](3), float64(130), int32(64), int64(5), object(2)
memory usage: 304.0+ MB

In [8]:
df_full.head()

,Open,High,Low,Close,Adj Close_x,Volume,Dividends,Stock Splits,Ticker,Year,...,growth_brent_oil_7d,growth_brent_oil_30d,growth_brent_oil_90d,growth_brent_oil_365d,growth_btc_usd_1d,growth_btc_usd_3d,growth_btc_usd_7d,growth_btc_usd_30d,growth_btc_usd_90d,growth_btc_usd_365d
0,0.088542,0.101563,0.088542,0.097222,0.059598,1.031789e+09,0.0,0.0,MSFT,1986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.097222,0.102431,0.097222,0.100694,0.061726,3.081600e+08,0.0,0.0,MSFT,1986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.100694,0.103299,0.100694,0.102431,0.062791,1.331712e+08,0.0,0.0,MSFT,1986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.102431,0.103299,0.098958,0.099826,0.061194,6.776640e+07,0.0,0.0,MSFT,1986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.099826,0.100694,0.097222,0.098090,0.060130,4.789440e+07,0.0,0.0,MSFT,1986,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_full.keys()

Index(['Open', 'High', 'Low', 'Close', 'Adj Close_x', 'Volume', 'Dividends',
       'Stock Splits', 'Ticker', 'Year',
       ...
       'growth_brent_oil_7d', 'growth_brent_oil_30d', 'growth_brent_oil_90d',
       'growth_brent_oil_365d', 'growth_btc_usd_1d', 'growth_btc_usd_3d',
       'growth_btc_usd_7d', 'growth_btc_usd_30d', 'growth_btc_usd_90d',
       'growth_btc_usd_365d'],
      dtype='object', length=204)

In [11]:
# growth indicators (but not future growth): growth from current till previous x days
GROWTH = [g for g in df_full.keys() if (g.find('growth_')==0)&(g.find('future')<0)]
print(GROWTH)

['growth_1d', 'growth_3d', 'growth_7d', 'growth_30d', 'growth_90d', 'growth_365d', 'growth_dax_1d', 'growth_dax_3d', 'growth_dax_7d', 'growth_dax_30d', 'growth_dax_90d', 'growth_dax_365d', 'growth_snp500_1d', 'growth_snp500_3d', 'growth_snp500_7d', 'growth_snp500_30d', 'growth_snp500_90d', 'growth_snp500_365d', 'growth_dji_1d', 'growth_dji_3d', 'growth_dji_7d', 'growth_dji_30d', 'growth_dji_90d', 'growth_dji_365d', 'growth_epi_1d', 'growth_epi_3d', 'growth_epi_7d', 'growth_epi_30d', 'growth_epi_90d', 'growth_epi_365d', 'growth_gold_1d', 'growth_gold_3d', 'growth_gold_7d', 'growth_gold_30d', 'growth_gold_90d', 'growth_gold_365d', 'growth_wti_oil_1d', 'growth_wti_oil_3d', 'growth_wti_oil_7d', 'growth_wti_oil_30d', 'growth_wti_oil_90d', 'growth_wti_oil_365d', 'growth_brent_oil_1d', 'growth_brent_oil_3d', 'growth_brent_oil_7d', 'growth_brent_oil_30d', 'growth_brent_oil_90d', 'growth_brent_oil_365d', 'growth_btc_usd_1d', 'growth_btc_usd_3d', 'growth_btc_usd_7d', 'growth_btc_usd_30d', 'growth_btc_usd_90d', 'growth_btc_usd_365d']

In [12]:
OHLCV = ['Open','High','Low','Close','Adj Close_x','Volume']
CATEGORICAL = ['Month', 'Weekday', 'Ticker', 'ticker_type']

In [13]:
TO_PREDICT = [g for g in df_full.keys() if (g.find('future')>=0)]
TO_PREDICT

['growth_future_30d', 'is_positive_growth_30d_future']

In [78]:
TO_DROP = ['Year','Date','index_x', 'index_y', 'index', 'Quarter','Adj Close_y'] + CATEGORICAL + OHLCV
TO_DROP

['Year',
 'Date',
 'index_x',
 'index_y',
 'index',
 'Quarter',
 'Adj Close_y',
 'Month',
 'Weekday',
 'Ticker',
 'ticker_type',
 'Open',
 'High',
 'Low',
 'Close',
 'Adj Close_x',
 'Volume']

In [79]:
# let's define on more custom numerical features
df_full['ln_volume'] = df_full.Volume.apply(lambda x: np.log(x))
     

# manually defined features
CUSTOM_NUMERICAL = ['SMA10', 'SMA20', 'growing_moving_average', 'high_minus_low_relative','volatility', 'ln_volume']
     

# All Supported Ta-lib indicators: https://github.com/TA-Lib/ta-lib-python/blob/master/docs/funcs.md
TECHNICAL_INDICATORS = ['adx', 'adxr', 'apo', 'aroon_1','aroon_2', 'aroonosc',
 'bop', 'cci', 'cmo','dx', 'macd', 'macdsignal', 'macdhist', 'macd_ext',
 'macdsignal_ext', 'macdhist_ext', 'macd_fix', 'macdsignal_fix',
 'macdhist_fix', 'mfi', 'minus_di', 'mom', 'plus_di', 'dm', 'ppo',
 'roc', 'rocp', 'rocr', 'rocr100', 'rsi', 'slowk', 'slowd', 'fastk',
 'fastd', 'fastk_rsi', 'fastd_rsi', 'trix', 'ultosc', 'willr',
 'ad', 'adosc', 'obv', 'atr', 'natr', 'ht_dcperiod', 'ht_dcphase',
 'ht_phasor_inphase', 'ht_phasor_quadrature', 'ht_sine_sine', 'ht_sine_leadsine',
 'ht_trendmod', 'avgprice', 'medprice', 'typprice', 'wclprice']
     

TECHNICAL_PATTERNS = [g for g in df_full.keys() if g.find('cdl')>=0]
print(f'Technical patterns count = {len(TECHNICAL_PATTERNS)}, examples = {TECHNICAL_PATTERNS[0:5]}')

C:\Users\DELL\AppData\Local\Temp\ipykernel_24008\4148861093.py:2: RuntimeWarning: divide by zero encountered in log
  df_full['ln_volume'] = df_full.Volume.apply(lambda x: np.log(x))

Technical patterns count = 61, examples = ['cdl2crows', 'cdl3blackrows', 'cdl3inside', 'cdl3linestrike', 'cdl3outside']

In [80]:
MACRO = ['gdppot_us_yoy', 'gdppot_us_qoq', 'cpi_core_yoy', 'cpi_core_mom', 'FEDFUNDS',
 'DGS1', 'DGS5', 'DGS10']
     

NUMERICAL = GROWTH + TECHNICAL_INDICATORS + TECHNICAL_PATTERNS + CUSTOM_NUMERICAL + MACRO
     

# CHECK: NO OTHER INDICATORS LEFT
OTHER = [k for k in df_full.keys() if k not in OHLCV + CATEGORICAL + NUMERICAL + TO_DROP]
OTHER
     
['growth_future_5d', 'is_positive_growth_5d_future']

print(f"Unique Tickers: {df_full.Ticker.nunique()}")

Unique Tickers: 33

In [81]:
# tickers, min-max date, count of daily observations
df_full.groupby(['Ticker'])['Date'].agg(['min','max','count'])

                     min        max  count
Ticker
AAPL          1980-12-12 2025-06-16  11218
ACN           2001-07-19 2025-06-16   6013
AMZN          1997-05-15 2025-06-16   7066
ASML          1995-03-15 2025-06-16   7615
AVGO          2009-08-06 2025-06-16   3990
BHARTIARTL.NS 2002-07-01 2025-06-16   5699
BRK-B         1996-05-09 2025-06-16   7323
CDI.PA        1992-01-27 2025-06-16   8611
GOOG          2004-08-19 2025-06-16   5240
HDB           2001-07-20 2025-06-16   6012
HINDUNILVR.NS 1996-01-01 2025-06-16   7397
IBN           2000-03-28 2025-06-16   6343
IDEXY         2010-01-20 2025-06-16   3876
INFY          1999-03-11 2025-06-16   6608
ITC.NS        1996-01-01 2025-06-16   7394
JPM           1980-03-17 2025-06-16  11406
LICI.NS       2022-05-17 2025-06-16    762
LLY           1972-06-01 2025-06-16  13372
LT.NS         2002-07-01 2025-06-16   5702
MC.PA         2000-01-03 2025-06-16   6541
META          2012-05-18 2025-06-16   3288
MSFT          1986-03-13 2025-06-16   9892
NVDA          1999-01-22 2025-06-16   6641
NVO           1981-04-30 2025-06-16  11123
OR.PA         2000-01-03 2025-06-16   6541
RELIANCE.NS   1996-01-01 2025-06-16   7394
RMS.PA        2000-01-03 2025-06-16   6541
SAP           1995-09-18 2025-06-16   7486
SBIN.NS       1996-01-01 2025-06-16   7395
SIE.DE        1996-11-08 2025-06-16   7327
TCS.NS        2002-08-12 2025-06-16   5670
TTE           1991-10-25 2025-06-16   8470
V             2008-03-19 2025-06-16   4339

In [82]:
# truncated df_full with 25 years of data (and defined growth variables)
df = df_full[df_full.Date>='2000-01-01']
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 191828 entries, 3490 to 5701
Columns: 205 entries, Open to ln_volume
dtypes: datetime64[ns](3), float64(131), int32(64), int64(5), object(2)
memory usage: 254.7+ MB

### Generating Dummies